import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "@ant-design/v5-patch-for-react-19";
import "@/public/fonts/iconfont.css";
import "./globals.css";

import Providers from "@/components/Provider";
const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" className="light" style={{ colorScheme: "light" }}>
      <head>
        <script
          type="text/javascript"
          src={`//api.map.baidu.com/api?type=webgl&v=1.0&ak=mzBY3pLQTnguP3a9yriGkb3sRPoidbNE`}
          async
          defer
        ></script>
      </head>
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased m-4  mb-15 `}
      >
        <Providers>{children}</Providers>
      </body>
    </html>
  );
}
